- name: adding roboshop user
  ansible.builtin.user:
    name: roboshop
- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: "download {{component}} code from nexus"
  ansible.builtin.get_url:
    url: "http://{{ lookup('env', 'admin') }}:{{ lookup('env', 'sowji123') }}@18.232.92.67:8081/repository/catalogue/com/roboshop/catalogue/{{ app_version }}/catalogue-{{ app_version }}.zip"
    dest: /tmp
- name: unzipping code in app directory
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}-{{app_version}}.zip"
    dest: /app
    remote_src: yes