- name: adding roboshop user
  ansible.builtin.user:
    name: roboshop
- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: Download artifact from nexus
  ansible.builtin.get_url:
    url: "{{NEXUS_URL}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
    dest: /tmp
    headers:
      Authorization: "Basic {{ 'admin:sowji123' | b64encode }}"
  register: download_result

- name: unzipping code in app directory
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}-{{app_version}}.zip"
    dest: /app
    remote_src: yes