- name: disabling current version and enabling nodejs18 version
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y ;
- name: installing nodejs18 version
  ansible.builtin.dnf:
   name: nodejs
   state: present
